name: amptools
channels:
- conda-forge
- defaults
dependencies:
- ipython
- jupyter
- lxml
- matplotlib
- numpy
- obspy
- pandas
- pytest
- pytest-cov
- python=3.5
- pyyaml
- xlrd
- xlwt
- openpyxl
- obspy
- xlsxwriter
